/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package multiwarehouse.ecommerce.payment.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum PaymentMethod implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethod> {
  DEBIT, CREDIT, CASH, QRIS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentMethod\",\"namespace\":\"multiwarehouse.ecommerce.payment.avro.model\",\"symbols\":[\"DEBIT\",\"CREDIT\",\"CASH\",\"QRIS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
