/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package multiwarehouse.ecommerce.payment.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum PaymentStatus implements org.apache.avro.generic.GenericEnumSymbol<PaymentStatus> {
  ONPROCESS, SUCCESS, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"namespace\":\"multiwarehouse.ecommerce.payment.avro.model\",\"symbols\":[\"ONPROCESS\",\"SUCCESS\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
