services:
  zookeper:
    image: ${KAFKA_IMAGE}:${KAFKA_VERSION}
    hostname: zookeper
    container_name: zookeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEPER_INIT_LIMIT: 5
      ZOOKEPER_SYNC_LIMIT: 2
      ZOOKEPER_SERVERS: zookeper:2888:3888
      KAFKA_OPTIONS: "Dzookeper.4lw.commands.whitelist=ruok"
    volumes:
      - "./volumes/zookeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeper/transactions:/var/lib.zookeper/log"